version: '3.8'

services:
  # Development service
  wavebox-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8079}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  # Production service
  wavebox-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8079}
    restart: unless-stopped
